# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
files: "pya/"
repos:

-   repo: "https://github.com/pre-commit/pre-commit-hooks"
    rev: v4.3.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
        args: [--unsafe]
    -   id: check-added-large-files
    -   id: debug-statements
        language_version: python3

-   repo: "https://github.com/asottile/reorder_python_imports"
    rev: v3.8.3
    hooks:
    -   id: reorder-python-imports

