language: generic

branches:
  only:
    - master
    - develop
    - dev-travis

install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-$TRAVIS_OS-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda config --append channels conda-forge
  - conda create -q -n test-environment python=$PYTHON_VERSION ffmpeg coverage python-coveralls --file=requirements.txt --file=requirements_test.txt
  - conda activate test-environment
  - pytest --version

script: pytest --cov pya/
after_success:
  - coveralls --config_file .coveragerc

env:
  global:
    AUDIODEV=null

jobs:
  include:
    - os: linux
      python: 3.7
      addons:
        apt:
          packages:
            - portaudio19-dev
      env:
        - TRAVIS_OS=Linux
        - PYTHON_VERSION=3.7
    - os: osx
      python: 3.7
      env:
        - TRAVIS_OS=MacOSX
        - PYTHON_VERSION=3.7
