# Tox configuration file
# Read more under https://tox.wiki/

[tox]
minversion = 3.24
envlist = default


[testenv:{tests}]
description = Invoke pytest to run automated tests
setenv =
    TOXINIDIR = {toxinidir}
skip_install = true
allowlist_externals = uv
commands =
    uv run pytest {posargs}

[testenv:{build,clean}]
description =
    build: Build the package in isolation according to PEP517, see https://github.com/pypa/build
    clean: Remove old distribution files and temporary build artifacts (./build and ./dist)
# https://setuptools.pypa.io/en/stable/build_meta.html#how-to-use-it
skip_install = True
allowlist_externals = uv
changedir = {toxinidir}
commands =
    clean: python -c 'import shutil; [shutil.rmtree(p, True) for p in ("build", "dist", "docs/_build")]'
    clean: python -c 'import pathlib, shutil; [shutil.rmtree(p, True) for p in pathlib.Path("src").glob("*.egg-info")]'
    build: uv build {posargs}


[testenv:{docs,doctests,linkcheck}]
description =
    docs: Invoke sphinx-build to build the docs
    doctests: Invoke sphinx-build to run doctests
    linkcheck: Check for broken links in the documentation
allowlist_externals = uv
setenv =
    DOCSDIR = {toxinidir}/docs
    BUILDDIR = {toxinidir}/docs/_build
    docs: BUILD = html
    doctests: BUILD = doctest
    linkcheck: BUILD = linkcheck
    # ^  requirements.txt shared with Read The Docs
commands =
    uv run sphinx-build -v --color -b {env:BUILD} -d "{env:BUILDDIR}/doctrees" "{env:DOCSDIR}" "{env:BUILDDIR}/{env:BUILD}" {posargs}


[testenv:publish]
description =
    Publish the package you have been developing to a package index server.
    By default, it uses testpypi. If you really want to publish your package
    to be publicly accessible in PyPI, use the `-- --repository pypi` option.
skip_install = True
allowlist_externals = uv
changedir = {toxinidir}
passenv =
    UV_PUBLISH_USERNAME
    UV_PUBLISH_PASSWORD
    UV_PUBLISH_URL
commands =
    uv publish {posargs}
